laptopcusmvc/Controllers/CustomizedlaptopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using laptopcusmvc.Models;
using laptopcusmvc.Helpers;
using tech4you.Models;

namespace webapp2mvc.Controllers
{
    public class CustomizedlaptopsController : Controller
    {
        helperAPI _api = new helperAPI();
        private readonly laptopContext _context;

        public CustomizedlaptopsController(laptopContext context)
        {
            _context = context;
        }

        // GET: Customizedlaptops
        public async Task<IActionResult> Report()
        {
            var laptopContext = _context.Customizedlaptops.Include(c => c.Display).Include(c => c.Os).Include(c => c.Processor).Include(c => c.Storagetype).Include(c => c.Warranty);
            return View(await laptopContext.ToListAsync());
        }

        // GET: Customizedlaptops/Details/5
        public async Task<IActionResult> invoice(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customizedlaptop = await _context.Customizedlaptops
                .Include(c => c.Display)
                .Include(c => c.Os)
                .Include(c => c.Processor)
                .Include(c => c.Storagetype)
                .Include(c => c.Warranty)
                .FirstOrDefaultAsync(m => m.Cuslaptopid == id);
            if (customizedlaptop == null)
            {
                return NotFound();
            }

            return View(customizedlaptop);
        }

        // GET: Customizedlaptops/Create
        public async Task<IActionResult> Customize(int id)
        {
            
            
            HttpClient cli = _api.Initial();
            var std1 = new Laptoplistmaster();
            
            Customizedlaptop stud = new Customizedlaptop();
            HttpResponseMessage result2 = await cli.GetAsync($"api/laptoplistmasters/{id}");
            HttpResponseMessage response = await cli.GetAsync($"api/Customizedlaptops/{id}");
            



            if (result2.IsSuccessStatusCode)
            {
                var res2 = result2.Content.ReadAsStringAsync().Result;
                
                string data = response.Content.ReadAsStringAsync().Result;
                std1 = JsonConvert.DeserializeObject<Laptoplistmaster>(res2);
                
            }
            
            ViewData["Brandname"] = std1.Brandname;
            ViewData["Processor"] = std1.Processor;
            ViewData["Memory"] = std1.Memory;
            ViewData["Os"] = std1.Os;
            ViewData["Productcolor"] = std1.Productcolor;
            ViewData["Storagetype"] = std1.Storagetype;
            ViewData["Laptopname"] = std1.Laptopname;
            ViewData["Price"] = std1.Price;
            ViewData["Antivirus"] = std1.Antivirus;
            ViewData["Display"] = std1.Display;
            ViewData["laptopimage"] = std1.Laptopimage;

            

            var demo = new SelectList(_context.Displaytbls, "Price", "Displaysize");
            var demo1 = new SelectList(_context.Displaytbls, "Displaysize", "Displaysize");
            var demo2 = new SelectList(_context.Displaytbls, "Displayid", "Displaysize");
            ViewData["Displayid"] = new SelectList(_context.Displaytbls, "Displayid", "Displaysize");
            ViewData["Osid"] = new SelectList(_context.Ostbls, "Osid", "Osname");
            ViewData["Processorid"] = new SelectList(_context.Processortbls, "Processorid", "Processorname");
            ViewData["Storagetypeid"] = new SelectList(_context.Storagetypetbls, "Storagetypeid", "Storagetypename");
            ViewData["Warrantyid"] = new SelectList(_context.Warrantytbls, "Warrantyid", "Warrantyperiod");
            return View();
        }



        // POST: Customizedlaptops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomizeAsync([Bind("Cuslaptopid,Cuslaptopname,Cusbrandname,Cusprice,Cusantivirus,Username,Email,Processorid,Displayid,Osid,Storagetypeid,Warrantyid,Quantity,Grandtotal,Purchasedate,Invoiceid")] Customizedlaptop customizedlaptop)
        {

            if (ModelState.IsValid)
            {
                _context.Add(customizedlaptop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Report));
            }
            ViewData["Displayid"] = new SelectList(_context.Displaytbls, "Displayid", "Displaysize", customizedlaptop.Displayid);
            ViewData["Osid"] = new SelectList(_context.Ostbls, "Osid", "Osname", customizedlaptop.Osid);
            ViewData["Processorid"] = new SelectList(_context.Processortbls, "Processorid", "Processorname", customizedlaptop.Processorid);
            ViewData["Storagetypeid"] = new SelectList(_context.Storagetypetbls, "Storagetypeid", "Storagetypename", customizedlaptop.Storagetypeid);
            ViewData["Warrantyid"] = new SelectList(_context.Warrantytbls, "Warrantyid", "Warrantyperiod", customizedlaptop.Warrantyid);
            return View(customizedlaptop);
        }

        // GET: Customizedlaptops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customizedlaptop = await _context.Customizedlaptops.FindAsync(id);
            if (customizedlaptop == null)
            {
                return NotFound();
            }
            ViewData["Displayid"] = new SelectList(_context.Displaytbls, "Displayid", "Displaysize", customizedlaptop.Displayid);
            ViewData["Osid"] = new SelectList(_context.Ostbls, "Osid", "Osname", customizedlaptop.Osid);
            ViewData["Processorid"] = new SelectList(_context.Processortbls, "Processorid", "Processorname", customizedlaptop.Processorid);
            ViewData["Storagetypeid"] = new SelectList(_context.Storagetypetbls, "Storagetypeid", "Storagetypename", customizedlaptop.Storagetypeid);
            ViewData["Warrantyid"] = new SelectList(_context.Warrantytbls, "Warrantyid", "Warrantyperiod", customizedlaptop.Warrantyid);
            return View(customizedlaptop);
        }

        // POST: Customizedlaptops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Cuslaptopid,Cuslaptopname,Cusbrandname,Cusprice,Cusantivirus,Username,Email,Processorid,Displayid,Osid,Storagetypeid,Warrantyid,Quantity,Grandtotal,Purchasedate,Invoiceid")] Customizedlaptop customizedlaptop)
        {
            if (id != customizedlaptop.Cuslaptopid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customizedlaptop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomizedlaptopExists(customizedlaptop.Cuslaptopid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Displayid"] = new SelectList(_context.Displaytbls, "Displayid", "Displaysize", customizedlaptop.Displayid);
            ViewData["Osid"] = new SelectList(_context.Ostbls, "Osid", "Osname", customizedlaptop.Osid);
            ViewData["Processorid"] = new SelectList(_context.Processortbls, "Processorid", "Processorname", customizedlaptop.Processorid);
            ViewData["Storagetypeid"] = new SelectList(_context.Storagetypetbls, "Storagetypeid", "Storagetypename", customizedlaptop.Storagetypeid);
            ViewData["Warrantyid"] = new SelectList(_context.Warrantytbls, "Warrantyid", "Warrantyperiod", customizedlaptop.Warrantyid);
            return View(customizedlaptop);
        }

        // GET: Customizedlaptops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customizedlaptop = await _context.Customizedlaptops
                .Include(c => c.Display)
                .Include(c => c.Os)
                .Include(c => c.Processor)
                .Include(c => c.Storagetype)
                .Include(c => c.Warranty)
                .FirstOrDefaultAsync(m => m.Cuslaptopid == id);
            if (customizedlaptop == null)
            {
                return NotFound();
            }

            return View(customizedlaptop);
        }

        // POST: Customizedlaptops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customizedlaptop = await _context.Customizedlaptops.FindAsync(id);
            _context.Customizedlaptops.Remove(customizedlaptop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomizedlaptopExists(int id)
        {
            return _context.Customizedlaptops.Any(e => e.Cuslaptopid == id);
        }
        public IActionResult Getprocessorprice()
        {

laptopcusmvc/Controllers/LaptoplistsmasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tech4you.Models;
using laptopcusmvc.Models;

namespace webapp2mvc.Controllers
{
    public class LaptoplistmastersController : Controller
    {
        private readonly laptopContext _context;

        public LaptoplistmastersController(laptopContext context)
        {
            _context = context;
        }

        // GET: Laptoplistmasters
        public async Task<IActionResult> Laptoplistsmaster()
        {
            return View(await _context.Laptoplistmasters.ToListAsync());
        }

        // GET: Laptoplistmasters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laptoplistmaster = await _context.Laptoplistmasters
                .FirstOrDefaultAsync(m => m.Laptopid == id);
            if (laptoplistmaster == null)
            {
                return NotFound();
            }

            return View(laptoplistmaster);
        }

        // GET: Laptoplistmasters/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Laptoplistmasters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Laptopid,Laptopname,Brandname,Price,Processor,Display,Os,Storagetype,Productcolor,Antivirus,Warranty,Laptopimage,Memory")] Laptoplistmaster laptoplistmaster)
        {
            if (ModelState.IsValid)
            {
                _context.Add(laptoplistmaster);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(laptoplistmaster);
        }

        // GET: Laptoplistmasters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laptoplistmaster = await _context.Laptoplistmasters.FindAsync(id);
            if (laptoplistmaster == null)
            {
                return NotFound();
            }
            return View(laptoplistmaster);
        }

        // POST: Laptoplistmasters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Laptopid,Laptopname,Brandname,Price,Processor,Display,Os,Storagetype,Productcolor,Antivirus,Warranty,Laptopimage,Memory")] Laptoplistmaster laptoplistmaster)
        {
            if (id != laptoplistmaster.Laptopid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(laptoplistmaster);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LaptoplistmasterExists(laptoplistmaster.Laptopid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(laptoplistmaster);
        }

        // GET: Laptoplistmasters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laptoplistmaster = await _context.Laptoplistmasters
                .FirstOrDefaultAsync(m => m.Laptopid == id);
            if (laptoplistmaster == null)
            {
                return NotFound();
            }

            return View(laptoplistmaster);
        }

        // POST: Laptoplistmasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var laptoplistmaster = await _context.Laptoplistmasters.FindAsync(id);
            _context.Laptoplistmasters.Remove(laptoplistmaster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LaptoplistmasterExists(int id)
        {
            return _context.Laptoplistmasters.Any(e => e.Laptopid == id);
        }
    }
}

laptopcusmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - laptopcusmvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js">
    </script>
</head>
<body>
    <header class="bg-dark headerb">
        <!--<nav class="header navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow navbar">
        <div class="container">
            <img src="~/lib/images/colorful-laptop-design-vector-illustration.jpg" width="50px"/>
            <a class="navbar-brand" asp-area="" asp-controller="Laptoplistsmaster" asp-action="Laptoplistsmaster">TECH4YOU</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class=" navbtn" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>-->
        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
        <!--<li class="nav-item">
                        <a class=" navbtn" asp-area="" asp-controller="Customizedlaptops" asp-action="Report">Report</a>
                    </li>
                    <li class="nav-item">
                        <a class=" navbtn" asp-area="" asp-controller="Home" asp-action="Index">Contact</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>-->
        <nav class="navbar-inverse headerb">
            <div class="container-fluid navbar-collapse collapse d-sm-inline-flex">
                
                <div class="navbar-header">

                    <a class="navbar-brand text-white" href="#">TECH4YOU</a>
                    <img src="~/lib/images/colorful-laptop-design-vector-illustration.jpg" width="50px" />
                </div>
                <ul class="nav navbar-nav navbar-collapse collapse d-sm-inline-flex">
                    <li class="nav-item">
                        <a class=" navbtn" asp-area="" asp-controller="Laptoplistmasters" asp-action="Laptoplistsmaster">Home</a>
                    </li>
                    @*<li class="nav-item">
            <a class="navbtn" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                    <li class="nav-item">
                            <a class=" navbtn" asp-area="" asp-controller="Customizedlaptops" asp-action="Report">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class=" navbtn" asp-area="" asp-controller="Laptoplistmasters" asp-action="Laptoplistsmaster">Contact</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div>
            <main>
                @RenderBody()
            </main>
        </div>

        @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - laptopcusmvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
    </html>